services:
    rmcgirr83.authorizedforurls.listener:
        class: rmcgirr83\authorizedforurls\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@user'
        tags:
            - { name: event.listener }
