services:
    rmcgirr83.authorizedforurls.listener:
        class: rmcgirr83\authorizedforurls\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
